#!/usr/bin/env bash
# Emulate with bochs.
bochs -n -q 'boot: a' \
            'floppya: 1_44=floppy.img, status=inserted' \
            'megs: 32' \
            'magic_break: enabled=1' \
            'cpuid: x86_64=1, simd=sse4_2'
