#!/usr/bin/env bash
# Create symbolic link of lit system into SBCL system directory.
bochs -n -q 'boot: a' \
            'floppya: 1_44=floppy.img, status=inserted' \
            'megs: 32' \
#            'cpuid: x86_64=1, sse=sse4_2, sep=1, apic=1' 

