#!/usr/bin/env bash
# Emulate with bochs.
bochs -n -q -rc bochs-debug-cmds \
      'boot: a' \
      'floppya: 1_44=floppy.img, status=inserted' \
      'megs: 32' \
      'magic_break: enabled=1' \
      'cpuid: x86_64=1' \
      'vga: extension=vbe' \
      'display_library: sdl2, options="fullscreen,gui_debug"'
